### ISSUE TITLE
LauncherIcon not rendered correctly and items in QAT can be removed from QAT in it's popup

### ISSUE THREAD

**Issue by nkrs200** [fluentribbon/Fluent.Ribbon#1185] opened 2023-12-15 17:27 UTC
Hello,

It appears to me that when I am using the latest version of Fluent.Ribbon, it somehow uses the wrong icons for the launcher icons.
![image](https://github.com/fluentribbon/Fluent.Ribbon/assets/32461481/c3607b50-035e-4623-8e32-a2133578cb2b)
In the image above, the correct launcher icon (the default launcher icon) is displayed when the launcher icon variable is not set, but if it is set (like it is in the paragraph group), it would use the icon that is defined.

Also, I have noticed that when a ribbon group is added into the quick access, it doesn't open automatically as you have to click the edge of the box surrounding the icon (if there is one), and then from there, if that ribbongroup is shown, the ribbon group disappears from the ribbon.
![image](https://github.com/fluentribbon/Fluent.Ribbon/assets/32461481/f09fd35c-c772-4d0d-a8bb-dabdbff8d723)
Image above is hovering over the image on the ribbon.
![image](https://github.com/fluentribbon/Fluent.Ribbon/assets/32461481/a17ddfe4-0945-46fd-9a0c-f76c858f719b)
When the edge of the button is clicked.
![image](https://github.com/fluentribbon/Fluent.Ribbon/assets/32461481/f2072685-87cb-47ea-95ab-8656c52d1591)
Somehow found another bug where the launcher icon disappears if you add it from the "Add to Quick Access Toolbar" command when the popup menu is shown.  Not sure how it became empty.
![image](https://github.com/fluentribbon/Fluent.Ribbon/assets/32461481/9a8acf3c-43d4-47db-80da-0896f2352fa1)
And... there it goes after opening and closing it a few times...

Also here is a few videos that shows exactly everything that I did.
[Media3.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/13688094/Media3.zip)

Attached is a zip of the project file that I used below.
[RibbonTests.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/13688060/RibbonTests.zip)

Just for a little side note:  The RibbonGroupBox item in the Quick Access Toolbar issue is also in as far back as Fluent.Ribbon 8.0.0.

I hope this helps!

---
Environment:
- Fluent.Ribbon 10.0,4
- Windows 10 21H2
- .NET Framework v4.6.2

**Comment by batzen** [comment] 2023-12-27 08:56
Hi there,

your launcher icons don't render properly because you seem to have something wrong in your rendering code for those.
That's not a bug in Fluent.Ribbon.

Having to click the edge of the group in the QAT is caused by the icon being hittest visible. I will change the `IconPresenter` to not be visible for hit testing in the next version. You can also fix it for your icons by setting `IsHitTestVisible` to `false` while waiting for the next version.

The disappearing launcher icon is caused by a bug in Fluent.Ribbon as visual can only have one parent control. The QAT works by moving/cloning controls to the QAT popup. As your launcher icon is a visual that one only renders in the popup, but disappears from the real control.
I will fix this by using a visual brush if the launcher icon is a visual. That's the way the icon get's cloned also.
In case of your icons that leads to the icon not being rendered in the popup as using your control as a visual brush does not seem to work.

The disappearing group items issue is also a bug in Fluent.Ribbon an will be fixed in the next version.

**Closed** 2024-02-03 06:29 UTC
Labels: Bug :lady_beetle:
