### ISSUE TITLE
Black flicker on complete window-area when resizing

### ISSUE THREAD

**Issue by holgerschm** [fluentribbon/Fluent.Ribbon#307] opened 2016-04-19 14:48 UTC
When resizing the window the complete window area is flickering(black) at a high rate. This is very annoying - it renders the library unusable.

The flicker was gone with the 4.0.1(unfortunately the is an issue with the window border in 4.0.1) release but reappered in the 4.0.3 release.

The rate of flickering seems to depends on the content of the window. On an emty window except for the ribbon it flickers 1-3 times per resize. When the window is filled with controls the flickering happens on every frame.
### Environment
- Fluent.Ribbon v4.0.3.394
- Theme Office2013
- Windows 7 x64
- .NET Framework 4.6.1

**Comment by batzen** [comment] 2016-04-19 16:55
Does this happen on vertical or horizontal resize?

**Comment by holgerschm** [comment] 2016-04-20 08:56
This happens on all (8) resizes.
I did some more testing:
The flicker rates depend on the total size of the window. I use two 1920x1200 screens. When the window has the size of a 1/4 screen there is (almost) no flickering. When the window spans over both screens there is a lot of flickering. I will try to narrow it down further ...

**Comment by holgerschm** [comment] 2016-04-20 09:56
Here is some more info:
It depends on the type and count of controls in the window:
400 Buttons -> no flickering
400 TextBoxes -> no flickering
400 Ellipses -> no flickering
400 Labels -> a lot of flickering
4 Labels -> some flickering
100000 Labels -> no flickering !

Very strange...

**Comment by batzen** [comment] 2016-04-23 11:17
That's strange and i don't think it's caused by the ribbon.
Does this only happen when you are using a RibbonWindow?

**Comment by holgerschm** [comment] 2016-04-25 10:12
I did more testing on 8 different systems (all running Windows 7). All showed black flickering on the RibbonWindow when using the default windows 7 theme. But I found out that the flicker is gone when switching to "Classic" theme!

None of them shows flickering on default WPF Windows (Or any other application not using fluent ribbon).

I am pretty sure this has someting to do with the fluent ribbon. But maybe dependend on the windows version and the graphics hardware?

**Comment by batzen** [comment] 2016-04-25 15:07
Will try to find a windows 7 machine at work and try to reproduce it.

WPF depends on the graphics hardware and so does DWM.
Windows version is relevant because DWM/non DWM behaves very different when it comes to window drawing.

**Comment by batzen** [comment] 2018-07-04 17:48
Flicker should be gone as soon as the GlowWindow branch is merged.

**Comment by batzen** [comment] 2018-07-07 13:54
GlowWindow branch + PR merged. This should be fixed now.

**Closed by batzen** 2018-07-07 13:54 UTC
Labels: Bug :beetle:, WindowChrome
