### ISSUE TITLE
The title bar of the window is black and buttons does not displayed after resizing the window

### ISSUE THREAD

**Issue by Judy10** [fluentribbon/Fluent.Ribbon#351] opened 2016-09-22 12:55 UTC
## 
### Environment
- Fluent.Ribbon v 4.0.3
- Theme office 2013
- Windows 7
- .NET Framework 4.0

when resizing the window to very small height and big width - sometimes the title bar becomes black and without minimize/maximize/close buttons. it happens only with 2 screens.
another case: when working with TeamViewer or remote desktop - it also happens.

normal case:
![image](https://cloud.githubusercontent.com/assets/18466029/18748303/51913dc4-80da-11e6-86cf-81f119ad0266.png)
bug case:
![image](https://cloud.githubusercontent.com/assets/18466029/18748829/c913a100-80dc-11e6-860b-0bb93baaa1ef.png)

**Comment by batzen** [comment] 2016-10-01 09:14
I got no Windows 7 machines anymore and DWM is disabled in Hyper-V...
Is anyone able to have a look at this issue?

**Comment by chdft** [comment] 2016-10-03 03:26
I just had a look at this issue, here are my findings:
I tried to reproduce the bug both with the Office 2010 (the one which has 3 color variants and thick glass borders) and Office 2013 (the one with custom window buttons), because, judging by the screenshots, @Judy10  is actually using the 2010 theme.
I wasn't able to reproduce the issue with the Office 2013 theme.
I noticed, that the glass area at the top flickers black when resizing the window in the Office 2010 theme. However, this problem isn't caused by the window size directly - for me this only happens when my graphics card is fairly busy (i.e. because another application is doing something in the background). I suppose the issue appears for @Judy10 when the window is very wide, because more has to be redrawn in that case.
It is worth noting, that other applications that use extended aero borders (like Windows Explorer) have the same problem when resizing. Additionally the problem occurs when resizing in any direction and is visible on all newly drawn surfaces that *should* display as aero glass - though this surface is much smaller when resizing horizontally.
Nevertheless the window state buttons always reappeared for me, after I stopped resizing the Window - though I can imagine that the window may glitch out and keep the black top border (covering the window state buttons).

Ultimately this looks like an issue outside of Fluent.Ribbon, because it happens for other applications as well.

Here the information about the test machine, because it seems to matter:
- Windows 7 Professional 64bit
- Radeon HD 6870 graphics card
- Screen1: 1600*1200, 32bit, 60Hz
- Screen2: 2560*1440, 32bit, 60Hz

**Comment by Judy10** [comment] 2016-10-05 20:09
First thank you for reply.
I obviously used office 2010 themes. It was just a typo.
Do you have any idea of why my window keeps the black border? It happens for me in different 3 machines!
Alternatively, any idea how can i fix this?

**Comment by batzen** [comment] 2016-10-06 14:58
I don't think you can fix it.
Handling those cases is very difficult, just have a look at the [ControlzEx](https://github.com/ControlzEx/ControlzEx) library used modify the window.

As the office 2010 and windows 8 themes are gone in version 5 of fluent.ribbon, i would advice you to switch to the office 2013 theme.

**Comment by chdft** [comment] 2016-10-15 07:41
@Judy10: Can you elaborate on your setup?
- Which graphics hardware do you use?
- Depending on your graphics hardware, aero might not work properly when another application does _interesting_/unsupported things using Direct3D. Can you reproduce the issue when no other application is running (especially games and browsers)?
- Can you reproduce the issue with the Showcase application?
- Can you reproduce the issue with other applications that customize their window chrome, but don't use Fluent.Ribbon (like Office 2010, Windows Explorer or Firefox)?
- Have you installed a custom theme engine?
- Is another application painting additional buttons in the non-client area (i.e. a send to second desktop button)?
- Is another application capturing the screen or parts of it while resizing? (usual suspects are remote desktop tools)

PS: Apparently e-mail notifications are broken for me, sorry for the delayed reply.

**Comment by Judy10** [comment] 2016-10-25 12:06
This is what I found out:

- Graphics hardware: Intel(R) HD Graphics 4600

- I reproduced it when no other application is running.

- I reproduced it with the Showcase application.

- I didn't succeed to reproduce it with other applications. I tried with Windows Explorer and Chrome.

- I didn't  install a custom theme engine.

- No other application is running.

- As I wrote, it's also occurred for me when I use Team Viewer.  But in this case no other application is running.

It's look like when the window goes out from the screen bounds - this issue occurs. see screenshot:
![blackribbon](https://cloud.githubusercontent.com/assets/18466029/19685266/609245da-9ac4-11e6-85b7-b08e1cfe6d45.png)

**Comment by chdft** [comment] 2016-11-15 18:46
I finally got around to investigate further:
This is apparently an issue with Intel HD graphics cards when some power saver features are enabled. I was able to reliably (well it occurred 8 of 8 times) reproduce it on a ThinkPad W540 with the dedicated graphics card disabled. When disabling the power saving features (I used a utility by Lenovo to do so), the issue wasn't reproducible any more. It seems reasonable to assume that similar features are available (although maybe not exposed in the UI) on other systems using similar hardware.

As a result, I would conclude that this is a quirk in the Intel HD Graphics driver and therefore not feasible to fix or reliably work around. As @batzen already suggested, switching to a non-dwm theme for your application (i.e. the Office 2013 theme) is probably the way to go.
Alternatively, you could use a regular `Window` in place of a `RibbonWindow` - although you would loose contextual tab headers, the quick access toolbar above the ribbon and the client area aero glass effect. You can see an example of this in the showcase application when you click "Open Regular Window" in the tab "Tests".

**Comment by batzen** [comment] 2017-07-14 11:01
Closed as there is no DWM theme left.

**Closed by batzen** 2017-07-14 11:01 UTC
Labels: help wanted

**Comment by KyanWang** [comment] 2018-12-28 09:03
I have the same issue with 4.0.3 after unlock the screen and finally found it can be fixed by config the app.manifest file. Hope this can help other people.

```
<compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
    <application>
      <!-- A list of the Windows versions that this application has been tested on and is
           is designed to work with. Uncomment the appropriate elements and Windows will 
           automatically selected the most compatible environment. -->

      <!-- Windows Vista -->
      <!--<supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}" />-->

      <!-- Windows 7 -->
      <!--<supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}" />-->

      <!-- Windows 8 -->
      <!--<supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}" />-->

      <!-- Windows 8.1 -->
      <!--<supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}" />-->

      <!-- Windows 10 -->
      **<supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}" />**

    </application>
  </compatibility>
```
