### ISSUE TITLE
ApplicationMenu MenuItem right arrow => System.NullReferenceException

### ISSUE THREAD

**Issue by macyarounanoka** [fluentribbon/Fluent.Ribbon#597] opened 2018-08-01 06:19 UTC
xaml
        <Fluent:Ribbon >
            <Fluent:Ribbon.Menu>
                <Fluent:ApplicationMenu Header="File" Size="Middle">
                    <Fluent:MenuItem Header="New File" InputGestureText="Ctrl+N" />
・・・

New File  is Fluent.MenuItem without child elements

run program. 
click file.
(Popup ApplicationMenu)
Move with the arrow keys
Entering the right arrow with keyboard focus at New File raises an exception

=>'System.NullReferenceException' (Fluent.dll)
不明( jp )=>Unknown(us)
>	Fluent.dll!Fluent.MenuItem.OnKeyDown(System.Windows.Input.KeyEventArgs e) 行 663	C#
 	PresentationCore.dll!System.Windows.UIElement.OnKeyDownThunk(object sender, System.Windows.Input.KeyEventArgs e)	不明
 	PresentationCore.dll!System.Windows.Input.KeyEventArgs.InvokeEventHandler(System.Delegate genericHandler, object genericTarget)	不明
 	PresentationCore.dll!System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate handler, object target)	不明
 	PresentationCore.dll!System.Windows.RoutedEventHandlerInfo.InvokeHandler(object target, System.Windows.RoutedEventArgs routedEventArgs)	不明
 	PresentationCore.dll!System.Windows.EventRoute.InvokeHandlersImpl(object source, System.Windows.RoutedEventArgs args, bool reRaised)	不明
 	PresentationCore.dll!System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject sender, System.Windows.RoutedEventArgs args)	不明
 	PresentationCore.dll!System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs args)	不明
 	PresentationCore.dll!System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs args, bool trusted)	不明
 	PresentationCore.dll!System.Windows.Input.InputManager.ProcessStagingArea()	不明
 	PresentationCore.dll!System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs input)	不明
 	PresentationCore.dll!System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport inputReport)	不明
 	PresentationCore.dll!System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(System.IntPtr hwnd, System.Windows.Input.InputMode mode, int timestamp, System.Windows.Input.RawKeyboardActions actions, int scanCode, bool isExtendedKey, bool isSystemKey, int virtualKey)	不明
 	PresentationCore.dll!System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(ref System.Windows.Interop.MSG msg, ref bool handled)	不明
 	PresentationCore.dll!System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(ref System.Windows.Interop.MSG msg, System.Windows.Input.ModifierKeys modifiers)	不明
 	PresentationCore.dll!System.Windows.Interop.HwndSource.OnPreprocessMessage(object param)	不明
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback, object args, int numArgs)	不明
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, System.Delegate callback, object args, int numArgs, System.Delegate catchHandler)	不明
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority priority, System.TimeSpan timeout, System.Delegate method, object args, int numArgs)	不明
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.Invoke(System.Windows.Threading.DispatcherPriority priority, System.Delegate method, object arg)	不明
 	PresentationCore.dll!System.Windows.Interop.HwndSource.OnPreprocessMessageThunk(ref System.Windows.Interop.MSG msg, ref bool handled)	不明
 	PresentationCore.dll!System.Windows.Interop.HwndSource.WeakEventPreprocessMessage.OnPreprocessMessage(ref System.Windows.Interop.MSG msg, ref bool handled)	不明
 	WindowsBase.dll!System.Windows.Interop.ComponentDispatcherThread.RaiseThreadMessage(ref System.Windows.Interop.MSG msg)	不明
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame frame)	不明
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame frame)	不明
 	PresentationFramework.dll!System.Windows.Application.RunDispatcher(object ignore)	不明
 	PresentationFramework.dll!System.Windows.Application.RunInternal(System.Windows.Window window)	不明
 	PresentationFramework.dll!System.Windows.Application.Run(System.Windows.Window window)	不明
 	PresentationFramework.dll!System.Windows.Application.Run()	不明

Environment
Windows10 Pro(1803)
Visual Studio 2015 Update 3
Fluent.Ribbon 6.1.0.233
.NET Framework 4.6

**Comment by batzen** [comment] 2018-08-01 16:40
This is a duplicate of #562 and is already fixed in version 7.0. ;-)

**Closed by batzen** 2018-08-01 16:40 UTC
Labels: already fixed in newer version
