### ISSUE TITLE
How to use ApplicationMenu corretly?

### ISSUE THREAD

**Issue by MarcusEdward** [fluentribbon/Fluent.Ribbon#199] opened 2015-11-15 08:57 UTC
I try to use the ApplicationMenu, here's my code:

    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="147"/>
            <RowDefinition/>
            <RowDefinition Height="26"/>
        </Grid.RowDefinitions>
        <Fluent:Ribbon VerticalAlignment="Stretch">
            <Fluent:Ribbon.Menu>
                <Fluent:ApplicationMenu Header="File">
                    <Fluent:MenuItem Header="ABC"/>
                </Fluent:ApplicationMenu>
            </Fluent:Ribbon.Menu>
        </Fluent:Ribbon>
    </Grid>

But when I click the File menu, it show the ApplicationMenu in the wrong position, like this:
![image](https://cloud.githubusercontent.com/assets/15854904/11168062/21157422-8bb1-11e5-9b4d-8845c7a7a2e9.png)

Did I use it incorrectly or was this a bug?

**Comment by blackbeard9** [comment] 2015-11-15 09:17
my ribbon code looks almost the same, so your code should be okay. try deleting all your RowDefinitions, is the problem still there?

**Comment by MarcusEdward** [comment] 2015-11-15 11:06
I have tried what you said and it didn't work

**Comment by TheMegaMatt** [comment] 2015-11-15 12:04
try by setting the first row Height to "Auto"


2015-11-15 12:06 GMT+01:00 MarcusEdward <notifications@github.com>:

**Comment by MarcusEdward** [comment] 2015-11-15 13:37
it didn't work either

**Comment by TheMegaMatt** [comment] 2015-11-16 16:10
are you using the RibbonWindow? because the side of that window looks wierd

2015-11-15 14:37 GMT+01:00 MarcusEdward <notifications@github.com>:

**Comment by batzen** [comment] 2015-11-16 17:27
I can only reproduce this by moving the window to the edge of the screen...
@TheMegaMatt 
The weird border is caused by Windows 10. That issue will be fixed as soon as #185 is done.

**Comment by TheMegaMatt** [comment] 2015-11-16 18:26
I develop on the latest Win 10 build and never seen that
Il 16 nov 2015 6:27 PM, "Bastian Schmidt" <notifications@github.com> ha
scritto:

**Comment by batzen** [comment] 2015-11-16 18:32
Try the Windows 8 or Office 2010 theme and you will see the issue...

**Comment by batzen** [comment] 2015-11-18 17:22
Any chance that you can try it on a different machine, to exclude that issue factor, and/or create a repro? I am unable to reproduce the issue here.

**Comment by batzen** [comment] 2015-12-01 16:06
Any news?

**Comment by batzen** [comment] 2015-12-17 14:42
Any news?

**Comment by batzen** [comment] 2015-12-22 12:58
Any news? @MarcusEdward

**Closed** 2015-12-30 16:51 UTC
Labels: waiting for response
