### ISSUE TITLE
How to change background color for ribbon? 

### ISSUE THREAD

**Issue by Mathanvj44** [fluentribbon/Fluent.Ribbon#613] opened 2018-08-21 09:51 UTC
Hi,

     How to change the background color for ribbon.  It is dark grey color but I want it into red.  But I didn't find which place I have to go and changed???  

---
### Environment

- Fluent.Ribbon4.5
- Windows _7
- .NET Framework 4.6.01590

**Comment by batzen** [comment] 2018-08-22 16:39
This is a duplicate of #609.

**Closed** 2018-08-22 16:39 UTC
Labels: Duplicate
