### ISSUE TITLE
BackStage flickering when opening

### ISSUE THREAD

**Issue by QuantumDeveloper** [fluentribbon/Fluent.Ribbon#112] opened 2015-05-14 14:42 UTC
I faced with the issue when Backstage is flickering in left top corner during opening.
OS - Win 7
.Net 4.5
Ribbon lib - 3.4

**Comment by batzen** [comment] 2015-05-18 08:45
What do you mean with "flickering"?
On my machines it works perfectly fine.
Could you post a video of that issue?

**Comment by QuantumDeveloper** [comment] 2015-05-18 09:26
https://onedrive.live.com/?cid=650F345C1F75A314&id=650f345c1f75a314%21105

Please, pay attention to the top left corner.

**Comment by batzen** [comment] 2015-05-19 06:43
Indeed, it does flicker a bit.
Anyone willing to invest time fixing this?

**Comment by batzen** [comment] 2015-05-20 11:00
A had some time to try this on my machines and there is no flickering.
I can see the flickering in your video but not on my machines.
Anyone else seeing this? Maybe it's related to some missing Windows updates or outdated/different video drivers?
In fact the whole left blue part is a single rect...

**Comment by QuantumDeveloper** [comment] 2015-05-20 11:02
@batzen this could be, but I see it in my work and home PC with different GPU (nvidia, AMD)

**Comment by batzen** [comment] 2015-05-20 11:19
The problem is that i can't fix such an issue when i can't reproduce it...
It really looks like an WPF issue instead of a Ribbon issue.

**Comment by batzen** [comment] 2015-07-12 17:12
No one willing to invest time fixing this or at least creating a reliable repro?

**Comment by QuantumDeveloper** [comment] 2015-07-12 18:07
Do you have any ideas why it could be flickering exactly in that place?

**Comment by batzen** [comment] 2015-07-12 21:28
I guess it's the animation and the titlebar, but I don't know what's really causing this issue... As soon as the backstage is opened the titlebar, or parts of it, react to that change. Maybe it's one of the changes done to the titlebar that cause the flickering. You could try to reproduce the issue when you set "IsQuickAccessToolBarVisible" on the ribbon to "false". If the issue disappears we got a direction to follow. Walking through your video, picture by picture, I can see that the flickering area is opaque when the animation has not started yet and is opaque again when the animation is done.

**Comment by QuantumDeveloper** [comment] 2015-07-12 21:38
Just checked IsQuickAccessToolBarVisible. Its not the toolbar. No matter if I set visibility to true or false. Problem still exists. Do you also have such issue?

**Comment by batzen** [comment] 2015-07-13 07:52
As I said earlier I sadly can't reproduce it thus making fixing it extremely difficult.

**Comment by batzen** [comment] 2015-07-14 17:21
Just commited some changes to the backstage animation, maybe it's better now.
Could you verify if it got better?

**Comment by QuantumDeveloper** [comment] 2015-07-14 17:26
I need to compile latest version from sources?

**Comment by batzen** [comment] 2015-07-14 17:28
Will release version 3.4.2 later which contains the changes.

**Comment by QuantumDeveloper** [comment] 2015-07-14 17:32
ok, as soon as you release it, I will update, check and let you know

**Comment by batzen** [comment] 2015-07-14 17:47
Released.

**Comment by QuantumDeveloper** [comment] 2015-07-14 17:50
Just tested. Issue is still present. It flickers only in part, which is over a Quckaccesstoolbar.

**Comment by QuantumDeveloper** [comment] 2015-07-14 17:53
And if I set it under the ribbon, it will still flicker. So, I think we can exclude the quckaccess itself

**Comment by batzen** [comment] 2015-07-14 18:04
At least we found out that it's not the toolbar...

**Comment by batzen** [comment] 2015-07-14 18:11
Could you try to change the width in the style to check if it's just that small area?
You would have to edit line 206 in Office2013\Controls\BackstageTabControl.xaml just increase width to 500 instead of Auto.

**Comment by QuantumDeveloper** [comment] 2015-07-14 18:15
OK, I will test it

**Comment by QuantumDeveloper** [comment] 2015-07-14 19:26
Seems I underatnd why it is flickering. I have the following code on backstage:
```
 <fluent:Backstage >
                  <fluent:BackstageTabControl>
                     <fluent:BackstageTabItem Header="Открыть" DataContext="{Binding Path=RibbonViewModel.FileBrowserOpenViewModel}">
                        <fluent:BackstageTabItem.Content>
                              <ribbon:FileBrowserView />
                        </fluent:BackstageTabItem.Content>
                     </fluent:BackstageTabItem>
                     <fluent:BackstageTabItem Header="Импорт" DataContext="{Binding Path=RibbonViewModel.FileBrowserImportViewModel}">
                        <fluent:BackstageTabItem.Content>
                              <ribbon:FileBrowserView />
                        </fluent:BackstageTabItem.Content>
                     </fluent:BackstageTabItem>
                  </fluent:BackstageTabControl>

               </fluent:Backstage>
```

If I remove items, it opens without flickering, but if at least one item is present, it will flicker. Maybe something is going on while my custom controls is loading?

**Comment by batzen** [comment] 2015-07-14 20:14
I would guess so. Any chance you can provide them for a repro?

**Comment by QuantumDeveloper** [comment] 2015-07-14 20:18
It will be hard to present you a full repro, but I will try

**Comment by QuantumDeveloper** [comment] 2015-07-16 19:02
Hi, here is my re[ro project for this issue. Could you please look at it?
https://onedrive.live.com/?id=650F345C1F75A314%21105&cid=650F345C1F75A314&group=0

**Comment by batzen** [comment] 2015-07-16 19:29
That indeed flickers really heavy. Will try to find out what's causing it, but that will take some time as I am away for the weekend.

**Comment by QuantumDeveloper** [comment] 2015-07-16 19:51
I hope you will fix this nasty bug

**Comment by batzen** [comment] 2015-07-21 15:53
It's the datagrid. But I don't know why...

**Comment by QuantumDeveloper** [comment] 2015-07-26 11:44
I know only one reason for flokering UI - its async UI updating.

**Comment by wstaelens** [comment] 2015-08-10 08:15
i have the same issue, glad I'm not the only one! :-)

**Comment by wstaelens** [comment] 2015-08-10 08:55
I have found that when the first BackstageTabItem is selected in the BackstageTabControl then it is flickering, when the second or other BackstageTabItem is selected when showing/hiding the backstage it is not flickering.

**Comment by QuantumDeveloper** [comment] 2015-08-10 09:41
Its not the showcase. I think real problem is that what actually hides under the tabitems. In my case I have the same control under first and seconds items and in both case I have flickering

**Comment by wstaelens** [comment] 2015-08-10 09:45
(old thread: https://github.com/fluentribbon/Fluent.Ribbon/issues/29 )

**Comment by floele-sp** [comment] 2015-11-06 08:44
I can see the same issue. I don't really see the reason why it flickers, but it would work if you made the following changes (Office 2013 theme):
1. Reduce top offset in BackstageAdorner to 24 
2. Then remove negative margin of the sidebar grid in BackstageTabControl.xaml (as far as I can see the negative margin is the source of the issue)
3. Increase the top margin of the Grid that hosts the backstage content by 24 and set the background color to BackstageBackgroundBrush
4. Remove background color of "grid" (otherwise the title bar won't be visible)

That retains the look of the backstage area while removing the flicker.

**Comment by batzen** [comment] 2015-11-06 10:06
Will have a look at your suggested changes.
Would be easier if you had created a PR for your changes and include changes for all themes.

**Comment by batzen** [comment] 2015-11-19 18:31
Could you please post the changes you made? It's quite difficult to follow those instructions.
Feel free to just post the whole code and xaml file here.

**Comment by batzen** [comment] 2015-11-19 22:12
Fixed with https://github.com/fluentribbon/Fluent.Ribbon/commit/909cf12db2af08d268f81178b1bbbc42cac162c9

**Closed by batzen** 2015-11-19 22:12 UTC
Labels: bug, help wanted, styles
