### ISSUE TITLE
Strange Ribbon Icon behaviour when using `DynamicResource`s

### ISSUE THREAD

**Issue by Splitwirez** [fluentribbon/Fluent.Ribbon#652] opened 2018-10-07 16:53 UTC
When Ribbon button Icons use `DynamicResource`s, the resources aren't found until the Ribbon is collapsed.
This can be seen here: https://i.imgur.com/ASRUBel.png
Top is before collapsing, bottom is after collapsing and re-expanding.

Repro: https://drive.google.com/uc?export=download&id=1GU5S1i2Cf5fyiBubOitILUIs27mRvrrr

Don't have time to finish typing this post rn but trying to get it out to you ASAP, will edit/update/clarify/whatever later
---
### Environment

- Fluent.Ribbon v6.1.0.326
- Windows 8.1
- .NET Framework 4.7.2

**Comment by batzen** [comment] 2018-10-07 18:17
I can't tell you the exact reason, but it might be caused by your custom window.
In general i made very negative experiences with including resources that should be global at the window level.
This would/should also remove the need to forward the window resources to your FileManagerControl.
Moving 
```
<ResourceDictionary Source="pack://application:,,,/RibbonFileManager;component/LightPlexBlue.xaml"/>
```
from the window to app.xaml fixes your issue.

By the way you should add 
```
Directory.CreateDirectory(Path.GetDirectoryName(_favoritesPath));
```
at line 35 of your Manager class, otherwise the app crashes on startup. ;-)

**Comment by batzen** [comment] 2018-11-05 16:55
Can we close this then? ;-)

**Comment by Splitwirez** [comment] 2018-11-05 17:10
Oh ijfioesjgojkiosdg sorry yeah go ahead

...um...yeah, moving it to the App resources worked perfectly. Thanks, and sorry about the mess.

**Closed** 2018-11-05 18:15 UTC
