### ISSUE TITLE
Binding error for RibbonProperties.MouseOverBackground

### ISSUE THREAD

**Issue by znakeeye** [fluentribbon/Fluent.Ribbon#500] opened 2018-01-14 23:09 UTC
I keep seeing this binding error when running my Ribbon application. How can you get rid of it?

`System.Windows.Data Error: 40 : BindingExpression path error: '(Fluent:RibbonProperties.MouseOverBackground)' property not found on 'object' ''RibbonTabItem' (Name='')'. BindingExpression:Path=(Fluent:RibbonProperties.MouseOverBackground); DataItem='RibbonTabItem' (Name=''); target element is 'RibbonTabItem' (Name=''); target property is 'Background' (type 'Brush')`

Using these themes:
```
<ResourceDictionary.MergedDictionaries>
  <ResourceDictionary Source="pack://application:,,,/Fluent;Component/Themes/Generic.xaml" />
  <ResourceDictionary Source="pack://application:,,,/Fluent;component/Themes/Accents/Cobalt.xaml" />
</ResourceDictionary.MergedDictionaries>
```
I tried setting that attached property on my RibbonTabItems, but it didn't help.

---
### Environment

- Fluent.Ribbon __v6.0.0-dev0171__
- Windows __10__
- .NET Framework __4.5.1__

**Comment by batzen** [comment] 2018-01-15 10:26
I observed the same when there was "only" .NET 4.5 or 4.6 installed.
Running on a machine having .NET 4.7 installed the error disappears.

In my case that just seemed to be a glitch in the .NET runtime and everything worked as expected regardless of the error.
Do the ribbon tab items have the proper mouse over effect on your machine? If that's the case you can safely ignore that error.

.NET sometimes seems to have problems resolving the attached property binding on the first try and succeeds on the following tries.

**Comment by znakeeye** [comment] 2018-01-15 20:48
Interesting! Though, the hover effect is not there. I tried setting the property to "Red" but my tabs are white no matter how much I hover them.

**Comment by batzen** [comment] 2018-01-17 18:52
That's strange.
I absolutely can't reproduce this and it should work as it's valid xaml...
Any chance you can try this on a different machine with a different .net version?

**Comment by batzen** [comment] 2018-01-21 10:37
Ok, i guess i found out what's causing this error.
Not adding `Path=` to the binding of an attached property sometimes can cause this issue.
Will fix it.

**Closed** 2018-01-21 10:49 UTC
Labels: bug
