### ISSUE TITLE
Ribbon in minimize mode cause .Net application to crash in windows 10

### ISSUE THREAD

**Issue by momer79** [fluentribbon/Fluent.Ribbon#604] opened 2018-08-06 18:22 UTC
Ribbon in minimize mode cause .Net application to crash in windows 10. It works fine in windows 7.

Here are the steps to reproduce this behaviour;

1- Click on the first tab
2- Minimize Ribbon (click on the minimize ribbon button)
3- Click on the second tab
4- Click on the button results in crashing application

Widows log;
Faulting application name: MyApp.Desktop.UI.exe, version: 2018.2.1, time stamp: 0x5b35085f
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc000041d
Fault offset: 0x0c5d60f0
Faulting process id: 0x640
Faulting application start time: 0x01d42da23eccc251
Faulting application path: C:\MyApp.Desktop.UI.exe
Faulting module path: unknown
Report Id: c378193e-079c-4f3d-8a3c-d0ef9dcd5809
Faulting package full name: 
Faulting package-relative application ID:  

MyApp.Desktop.UI.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Fluent.RibbonWindow.IsInRootPopup(System.Windows.DependencyObject)
   at Fluent.RibbonWindow.IsInRootPopup(System.Windows.DependencyObject)
   at Fluent.RibbonWindow.IsInRootPopup(System.Windows.DependencyObject)
   at Fluent.RibbonWindow.IsInRootPopup(System.Windows.DependencyObject)
   at Fluent.RibbonWindow.IsInRootPopup(System.Windows.DependencyObject)
   at Fluent.RibbonWindow.IsInRootPopup(System.Windows.DependencyObject)
   at Fluent.RibbonWindow.MouseWndProc(Int32, IntPtr, IntPtr) 
  

### Environment

- Fluent.Ribbon v4.0.30319 (version 2.0)
- Windows 10
- .NET Framework  supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5"/

**Comment by batzen** [comment] 2018-08-06 18:28
I can't reproduce this using the latest preview version from nuget.
Could you try to update to the latest preview version which is https://www.nuget.org/packages/Fluent.Ribbon/7.0.0-alpha0371 ?

**Comment by momer79** [comment] 2018-08-06 19:17
Thanks for your reply. Is there any way to hide or disable minimize button?

Also, i have just tested on other win 10 machine and Ribbon minimize button resize the whole application window. Why is it behaving differently on two different win 10 machines?

**Comment by batzen** [comment] 2018-08-06 19:34
You can set CanMinimize on the Ribbon.

But minimizing the ribbon should not move the window.
Which version of Fluent.Ribbon are you using?

**Comment by momer79** [comment] 2018-08-06 19:53
Fluent.Ribbon v4.0.30319 (version 2.0)

**Comment by batzen** [comment] 2018-08-06 20:36
v4.0.30319 is the .net version, not the version of fluent.ribbon.
You should at least use the latest stable version of fluent.ribbon which is 6.1.0.326.

**Comment by momer79** [comment] 2018-08-06 20:59
Its probably version 2.0.

Can i disable minimize button in version 2?

**Comment by batzen** [comment] 2018-08-07 06:26
Honestly i don't know. I don't remember. Version 2 is too old. Maybe there is a property on the window itself.

**Comment by batzen** [comment] 2018-08-21 08:45
Can we close this, or do you have any further questions?

**Closed** 2018-09-03 10:54 UTC
