### ISSUE TITLE
No Rezising at Fluent:RibbonContextualTabGroup at Version 5.0

### ISSUE THREAD

**Issue by langeth** [fluentribbon/Fluent.Ribbon#430] opened 2017-05-04 14:38 UTC
The Fluent:RibbonContextualTabGroup do not Rezise like Fluent:RibbonTabItem 

At Fullscreen the RibbonContextualTabGroup not following the RibbonTabItems
---
### Environment

- Fluent.Ribbon __v5.0.1__
- Theme __?__ (not needed in version 5.0 and upwards)
- Windows __10__
- .NET Framework __4.6__

**Comment by batzen** [comment] 2017-05-04 16:04
Will have a look at this as soon as i can. Which will, most probably, be next week.

**Comment by langeth** [comment] 2017-05-05 08:13
Sehr geehrter Herr Schmidt,


Im Ribbon.QuickAccessItems ist mir ebenfalls etwas aufgefallen:

Fluent.Ribbon 4.0.3.394
Themes/Office2010/Blue.xaml

[cid:image005.jpg@01D2C588.5DBAE800]

Hier konnten 4 Symbole angezeigt werden.



Fluent.Ribbon 4.0.3.394
Themes/Office2013/Generic.xaml

[cid:image006.jpg@01D2C588.5DBAE800]

Hier nur 3 Symbole und der Doppelpfeil ist beim ersten Start leer, erst nach dem 2ten öffnen wird das fehlende Symbol angezeigt.


Mit freundlichen Grüßen

Thomas Lange

Von: Bastian Schmidt [mailto:notifications@github.com]
Gesendet: Donnerstag, 4. Mai 2017 18:05
An: fluentribbon/Fluent.Ribbon <Fluent.Ribbon@noreply.github.com>
Cc: Thomas Lange <T.Lange@ra-micro.de>; Author <author@noreply.github.com>
Betreff: Re: [fluentribbon/Fluent.Ribbon] No Rezising at Fluent:RibbonContextualTabGroup at Version 5.0 (#430)


Will have a look at this as soon as i can. Which will, most probably, be next week.

**Comment by batzen** [comment] 2017-05-05 18:34
I tried to reproduce your issue from what i understood from your first issue but did not succeed in v6.0.
Could you add a image/video/gif showing the exact issue you are having?

Regarding your second issue: 
The images are missing from your answer. 
Does that still happen in version 5.0? I fixed a few rendering/layout issues in the QuickAccess area.

German:
Ich antworte hier auf Englisch, damit alle anderen unsere Konversation ebenfalls nachvollziehen können. Nicht falsch verstehen. ;-)

**Comment by langeth** [comment] 2017-05-08 05:57
Picture 1 with 4 Icons: blue.xaml
![image](https://cloud.githubusercontent.com/assets/20537969/25791885/937d4790-33c3-11e7-8aec-706d9772b42a.png)
Picture 2 with 3 Icons: generic.xaml - missing 1 Icon - it is at >> sign.
![image](https://cloud.githubusercontent.com/assets/20537969/25791925/c6abbb74-33c3-11e7-8be8-492eddbdbd1d.png)

**Comment by batzen** [comment] 2017-05-08 06:20
Ok, one icon more or less might be caused by different styles and thus different space requirements.
But the blank space on the left in Picture 2 looks strange.
Does this still look the same in version 5.0 or 6.0?

The Office 2010 theme is gone in 5.0, by the way.

**Comment by langeth** [comment] 2017-05-08 06:21
The left icon i deleted, so this is not the problem.

**Comment by langeth** [comment] 2017-05-08 06:22
I only tested it with version 5.0.

**Comment by langeth** [comment] 2017-05-08 09:30
The problems with Icon 3 or 4 are fixed with version 6.0.

**Comment by langeth** [comment] 2017-05-08 09:31
Tested with Version 6.0
Ribbon at Normal Windowmode:
![image](https://cloud.githubusercontent.com/assets/20537969/25798517/c7fc5e66-33e1-11e7-88d0-60d1b9201e05.png)
Ribbon at Fullscreen Windowmode:
![image](https://cloud.githubusercontent.com/assets/20537969/25798543/dec319c8-33e1-11e7-86a2-4c5b242a38f5.png)

**Comment by batzen** [comment] 2017-05-09 15:32
So there is only your fullscreen issue.
I can't reproduce the issue using the showcase application.
Is there any chance you can provide a repro for that?

**Comment by langeth** [comment] 2017-05-10 06:35
I use a Dockpanel around the <Fluent:Ribbon/>
<DockPanel.LayoutTransform>
            <ScaleTransform x:Name="ScaleTransform"
                            ScaleX="1"
                            ScaleY="1" />
</DockPanel.LayoutTransform>

and at Fullscreen i set ScaleX/Y to 1.6

**Comment by batzen** [comment] 2017-05-10 16:12
Ah, ok. Will try to reproduce the issue tomorrow using your hint.

**Comment by batzen** [comment] 2017-05-11 18:27
Ok, i can reproduce it. But it's not only the ContextualTabGroup not being scaled. It's the whole titlebar.

**Comment by batzen** [comment] 2017-05-11 18:36
The same problem exists in the sample application when you zoom it.
Will have a look at this.

**Comment by batzen** [comment] 2017-05-11 18:44
Forwarding the LayoutTransform to the template-parts seems impossible in stable manner.
The easiest way to get the whole window content being zoomed is

```
        public TestWindow()
        {
            this.InitializeComponent();

            this.Loaded += this.TestWindow_Loaded;
        }

        private void TestWindow_Loaded(object sender, RoutedEventArgs e)
        {
            ((FrameworkElement)VisualTreeHelper.GetChild(this, 0)).LayoutTransform = new ScaleTransform(1.6, 1.6);
        }
```

**Comment by batzen** [comment] 2017-05-17 19:59
@langeth Does that answer your question?

**Comment by langeth** [comment] 2017-05-18 05:38
I have not time at the moment to look about this.

**Comment by batzen** [comment] 2017-06-05 20:40
@langeth ping

**Comment by langeth** [comment] 2017-06-06 06:31
Not really. I use  
<DockPanel.LayoutTransform>
            <ScaleTransform x:Name="ScaleTransform"
                            ScaleX="1"
                            ScaleY="1" />
</DockPanel.LayoutTransform>
and then a Slider to Change the ScaleX and ScaleY.
Why it works with Fluent 4.03?

**Comment by batzen** [comment] 2017-06-06 10:07
Did it really work in 4.03? Tranforms should only get applied to the element itself and its children, but not to parents.

**Comment by langeth** [comment] 2017-06-06 11:32
Yes it works with Fluent.Ribbon 4.0.3.394 and 
Themes/Office2010/Blue.xaml

**Comment by batzen** [comment] 2017-06-06 12:47
Will have a look at it again.

**Comment by batzen** [comment] 2017-06-14 09:47
ok, it worked because parts of the titlebar were part of the ribbon.
In version 5 the titlebar was moved from the ribbon itself to the window.
Will have a look if i can fix that issue by forwarding the transforms.

**Comment by batzen** [comment] 2017-06-14 10:16
Have a partially working solution. There should be a way to forward it reliably. Should be fixed in version 6 this week.

**Closed** 2017-06-15 10:06 UTC

**Comment by batzen** [comment] 2017-06-15 10:08
`LayoutTransform` and `RenderTransform` can now be used directly on `RibbonWindow` as this now gets forwarded to the first template child of the window. Have a look at `TestWindow` in the showcase application for an example on how to use it.

**Comment by langeth** [comment] 2017-06-15 12:00
It works fine, thanks a lot batzen.
