### ISSUE TITLE
InRibbonGallery layout initially not correct

### ISSUE THREAD

**Issue by wstaelens** [fluentribbon/Fluent.Ribbon#318] opened 2016-05-18 07:03 UTC
![fluent ribbon inribbongallzery](https://cloud.githubusercontent.com/assets/7447285/15349938/871cfaea-1cd6-11e6-8cf0-e980d928057e.png)

the xaml:

```xaml
      <Fluent:InRibbonGallery MinItemsInRow="1" MaxItemsInRow="2"
                                Width="225" ItemWidth="100" ItemHeight="18"
                 Orientation="Horizontal" ItemsSource="{Binding AllThings}" SelectedItem="{Binding SelectedThing}">
          <Fluent:InRibbonGallery.ItemTemplate>
            <DataTemplate>
              <Grid>
                <Grid.ColumnDefinitions>
                  <ColumnDefinition Width="auto" />
                  <ColumnDefinition Width="*" />
                </Grid.ColumnDefinitions>
                <Rectangle Grid.Column="0" MinHeight="16" MinWidth="16" HorizontalAlignment="Center" Margin="3,0,3,0"
                           Fill="{Binding Data.Item2, Converter={conv:ColorToBrushConverter}, TargetNullValue={x:Static Colors.Pink}}" Stroke="Black" />
                <TextBlock Grid.Column="1" Text="{Binding Title}" HorizontalAlignment="Left" />
              </Grid>
            </DataTemplate>
          </Fluent:InRibbonGallery.ItemTemplate>
        </Fluent:InRibbonGallery>
```

I think I need some help with this layout issue. The first time my layout is always wrong but after cliking the popup of the InRibbonGallery the layout is correct.
(Based om some events and messages I create new ObservableCollection and assign it to the AllThings property.)

Any idea how I can get that layout initially correct?

--
### Environment WPF - Visual Studio 2015

- Fluent.Ribbon __v4.0.3.394
- Theme "/Fluent;Component/Themes/Office2013/Generic.xaml"
- Windows 10 x64
- .NET Framework __4.6__

**Comment by batzen** [comment] 2016-05-21 09:36
Could you try to reproduce this with version 5? I fixed a few things in GalleryPanel, which is used by InRibbonGallery internally.

**Comment by wstaelens** [comment] 2016-05-23 07:15
Is it available as pre-release on nuget?

**Comment by batzen** [comment] 2016-05-25 03:07
Currently not. I will try to find the time to publish one tomorrow.

**Comment by wstaelens** [comment] 2016-05-26 12:01
ok, looking forward to it.

**Comment by batzen** [comment] 2016-05-26 17:28
Instead of having to release to nuget i decided to provide access to the AppVeyor nuget feed.
Here you go https://ci.appveyor.com/nuget/fluent-ribbon

**Comment by batzen** [comment] 2016-06-09 18:20
@wstaelens Did you have the chance to try it?

**Comment by wstaelens** [comment] 2016-06-10 06:04
@batzen well actually have not found the time for it no. If it is in a nuget package I can quickly update it but other dll's need more work and can't afford this now at production.

**Comment by batzen** [comment] 2016-06-11 21:27
@wstaelens https://ci.appveyor.com/nuget/fluent-ribbon provides access to the nuget feed of fluent.ribbon on appveyor, so you get a nuget package from that.

**Comment by wstaelens** [comment] 2016-06-13 08:10
The issue is resolved by using the appveyor 5.x version.
but I can't use any themes anymore.

This crashes:
```xml
<ResourceDictionary Source="/Fluent;Component/Themes/Office2013/Generic.xaml" />
```
also this or this:
```xml
<ResourceDictionary Source="pack://application:,,,/Fluent;Component/Themes/Office2013/Generic.xaml" />
  <ResourceDictionary Source="pack://application:,,,/Fluent;Component/Themes/Windows8/Generic.xaml" />
```
Only one that works is this:
```xml
<ResourceDictionary Source="pack://application:,,,/Fluent;Component/Themes/Generic.xaml" />
```
some extra info:
```xml
        <ResourceDictionary Source="/Fluent;Component/Themes/Office2013/Generic.xaml" />
```

```
{"Cannot locate resource 'themes/office2013/generic.xaml'."}

An unhandled exception of type 'System.Windows.Markup.XamlParseException' occurred in PresentationFramework.dll

Additional information: 'Set property 'System.Windows.ResourceDictionary.Source' threw an exception.' Line number '9' and line position '10'.
```

What is the info on 5.x is it stable enough to use in production (known issues?)? when will be a full release?

**Comment by wstaelens** [comment] 2016-06-13 08:40
And the version 5.x also breaks most of my caliburn.micro MVVM actions, so can't use version 5.x. Don't know what is different:
```xml
        <Fluent:BackstageTabControl DataContext="{Binding}">
          <Fluent:Button Header="Options"
                         cal:Message.Attach="[Event Click] = [Action ShowOptions()]" />
```

**Comment by batzen** [comment] 2016-06-13 14:48
All themes, except the generic one, got remove. Please see #282 for the vote results and #301 for the removal. It's also noted in the changelog that those themes got removed.

As for your issue related to DataContext: The handling of logical children in WPF seems to be kinda buggy. I noticed that while fixing #315. See https://github.com/fluentribbon/Fluent.Ribbon/commit/3828f35fc42d4bbc076358aa52d1b233df26c2f2 and https://github.com/fluentribbon/Fluent.Ribbon/commit/9733f78c6abb7b6c078b9ff7696c3248d02bdb93 and https://github.com/fluentribbon/Fluent.Ribbon/commit/e2ee138abf9de00ce1996b55e7f9427d8f267b53 for details.

As of now there are no known issues, aside your DataContext issue. Would you mind creating a separate issue for that?

As you reported your issue with InRibbonGallery as fixed, can we close this issue?

**Comment by wstaelens** [comment] 2016-06-13 14:54
I don't have any issues now, as I've set the datacontext myself via relative source (don't know if this is a bug at your site that it doesn't work the same as in 4.x or not, so I don't know if I should create an issue for it).

you can close it yes.

**Closed** 2016-06-16 08:20 UTC
