### ISSUE TITLE
Maximizing/minimizing window with BackStage is incorrect

### ISSUE THREAD

**Issue by QuantumDeveloper** [fluentribbon/Fluent.Ribbon#77] opened 2015-03-04 08:07 UTC
Hello,

I am not sure if this is really Fluent bug, but do the following:
- Open non-maximized window
- Open backstage
- Maximize window
- Close backstage
- Restore window

As a result window will not back to the previous size and will become bigger, than it was at startup. Also it hangs and app becomes unstable. In my case the whole WPF UI is locked and become black when I try to move the window with the header.

**Comment by batzen** [comment] 2015-03-04 18:46
Can't reproduce here.
Does this also happen when you try this in the showcase application?
Which version are you using?
Which theme are you using?
Which windows version are you using?
Which .NET version are you using?

**Comment by QuantumDeveloper** [comment] 2015-03-04 19:55
You can easily reproduce this with the same test app from the last time:
https://onedrive.live.com/?cid=650F345C1F75A314&id=650F345C1F75A314%21105

In showcase app this is not reproducible
I am using the latest version - 3.3.0
Theme - office 2013
Windows - 8.1
.Net 4.5
But I also use fluent with MA.Metro 1.1.2. and use their MetroWindow as main window.

**Comment by batzen** [comment] 2015-03-04 20:38
Still can't reproduce with your application while following your steps. Anything missing?

**Comment by QuantumDeveloper** [comment] 2015-03-04 20:51
You must start app, open backstage, maximize window, close backstage and the press maximize button one more time to restore the previous size of the window.

**Comment by batzen** [comment] 2015-03-04 20:53
Ah, it's larger than before but it does not freeze.

**Comment by QuantumDeveloper** [comment] 2015-03-04 20:56
Yeah, I think it because of Win 7 or something like that. On Win 8.1 cant reproduce freezing hopefully.
So, does this ribbon issue or someone elses?

**Comment by batzen** [comment] 2015-03-04 20:58
It's larger because:
- When you open the backstage the window size is increase because there is a minimum window size required by the backstage (500x400 to be exact)
- When you close the backstage the original window size is restored
- But: Restoring/Changing the window size while the window is maximized has no effect on the normal window size
That's the simple reason why the window is larger than before.

**Comment by batzen** [comment] 2015-03-04 20:59
Regarding windows 7, I can try your sample at work as soon as I got time for that.

**Comment by batzen** [comment] 2015-03-04 21:00
Does the freezing only occur when you use the ribbon with the mah metro window?

**Comment by QuantumDeveloper** [comment] 2015-03-04 21:29
I didnt try it in other scenarios, but seems that exactly this use case leads to freezing, but here could be also PC configuration, so I would not say, that this is exactly ribbon fault.

But is this a bug or a normal behavior? As for me its unexpected behavior.

**Comment by batzen** [comment] 2015-03-05 12:16
Freezing is, of course, considered a bug.

Enlarging the window when the backstage is opened and restoring the window size when closed is the intended behavior but open for discussion if you feel it should be changed.

**Comment by QuantumDeveloper** [comment] 2015-03-05 12:26
Maybe you need to temporary persist previous state of the window before backstage and restore to that values when restoring the window size.

**Comment by batzen** [comment] 2015-03-05 12:27
That's exactly what is done but restoring the values while the window is maximized doesn't seem work in WPF...

**Comment by QuantumDeveloper** [comment] 2015-03-05 13:29
hm, how about:
```
private void MainWindow_StateChanged(object sender, EventArgs e)
      {
         if (WindowState == WindowState.Normal)
         {
            if (Backstage was open && lastWindowstate == maximized && lastWindowSize != currentWindowSIze)
            {
               Width = persistedWidth;
               Height = persistedHeight;
            }
         }
      }
```
This is just pveudo code, but seems it works. At least my window chane its size to size that I tell him.

**Comment by batzen** [comment] 2015-03-19 19:38
Hmmm, I checked the behavior of Word 2013 and it behaves the same.
Still considered a bug then?

**Comment by QuantumDeveloper** [comment] 2015-03-19 20:08
I also just tested on Word 2013 and I dont have such behaviuor. Window always correctly restore its size in described use case.

**Comment by batzen** [comment] 2015-03-27 17:46
While using Office 2013 on Windows 8.1 it behaves exactly as this library does.
Can anyone else try this out and tell us how it behaves?

**Comment by tbolon** [comment] 2015-10-27 22:27
FYI, it behaves the same on office 2013/win10. If you just open/close the backstage with a small window, it will adapt the size dynamically. But if you switch to maximized with the backstage open, it will not retain the previous size and switch back to windowed mode with the backstage size.

**Comment by batzen** [comment] 2015-10-29 08:49
As I said, we do exactly what Office 2013 does.

Does anyone disagree with closing this issue then?

**Closed** 2015-10-29 09:35 UTC
Labels: help wanted
