### ISSUE TITLE
maximizing in Win 10 

### ISSUE THREAD

**Issue by Bortxx** [fluentribbon/Fluent.Ribbon#267] opened 2016-02-13 18:46 UTC
When maximizing the application window on most of the themes in Win 10, there is a back border on left, right, and bottom of window. Seems like a layout bug.

**Comment by batzen** [comment] 2016-02-13 19:17
Which version are you using?
If you are not using the v4.0 preview, please try it.
If you are using the preview, please attach a screenshot here.

**Comment by Bortxx** [comment] 2016-02-13 20:22
Where do I get the v4.0 preview? I just downloaded the ZIP from the Code Tab on Github. Is v4.0 preview included there or do I get it from a different spot?

**Comment by batzen** [comment] 2016-02-13 21:09
You can grab the latest binaries from https://ci.appveyor.com/project/batzen/fluent-ribbon/build/artifacts

**Comment by Bortxx** [comment] 2016-02-13 22:48
Yes this version still has the problem. Notice the black border.



Also when maximized, border is there and some alignment issues. Placed against pink background so you can see it better.



And another problem in both versions, the application menu opens outside the application.



Perry

**Comment by batzen** [comment] 2016-02-14 09:16
Can't see screenshots in your response. I guess it's because you answered by mail.

In which themes do you see the issue?
Which build of windows 10 are you using?
Do you have multiple monitors? If yes, which resolutions are your monitors set to?
Can you download the following zip file, execute the contained exe file, hit the export button and attach  the file it created to this issue?
[PropertyAnalyzer.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/129602/PropertyAnalyzer.zip)
The tool creates a json file on your desktop.

**Comment by Bortxx** [comment] 2016-02-16 20:22
Yes this version still has the problem. Notice the black border.
<img width="287" alt="untitled" src="https://cloud.githubusercontent.com/assets/3203210/13089839/797c2ed2-d4a7-11e5-85b4-4f77194a765c.png">

Also when maximized, border is there and some alignment issues. Placed against pink background so you can see it better.
<img width="207" alt="untitled2" src="https://cloud.githubusercontent.com/assets/3203210/13089921/d9eb4be0-d4a7-11e5-83b3-071ec381e619.png">

And another problem in both versions, the application menu opens outside the application.
<img width="508" alt="untitled3" src="https://cloud.githubusercontent.com/assets/3203210/13089935/eb3f012a-d4a7-11e5-990a-f5c4a1fb0e8e.png">

**Comment by Bortxx** [comment] 2016-02-16 20:29
Can't see screenshots in your response. I guess it's because you answered by mail.

I responded on github with screenshots.

In which themes do you see the issue?

I don’t remember. It will be obvious from the screenshots.

Which build of windows 10 are you using?

Build 14257

Do you have multiple monitors? If yes, which resolutions are your monitors set to?

Not on my Win 10 machine where the screenshots where taken. It is a Surface Pro 3. Running 2160 x 1440 res.

Perry

**Comment by batzen** [comment] 2016-02-16 20:33
>  It is a Surface Pro 3. Running 2160 x 1440 res.

I guess that should be the information i needed.
Will try to reproduce the issue.

**Comment by Bortxx** [comment] 2016-02-16 20:36
Here is the file.

Perry

**Comment by batzen** [comment] 2016-02-16 20:38
The file is missing from your response.
When you respond by mail github seems to discard any attachments.

**Comment by Bortxx** [comment] 2016-02-16 20:43
Here is the file.
[PropertyAnalyzer_12-35-02.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/133268/PropertyAnalyzer_12-35-02.zip)

**Comment by batzen** [comment] 2016-02-17 17:29
So to clarify this for me:
You encounter the issue in version 3.6 and in version 4.0?
Just want to make sure it didn't get worse in 4.0.

I was unable to reproduce this issue so far. Will continue to try.

**Comment by Bortxx** [comment] 2016-02-17 18:37
There was no difference that I can notice between 3.6 and 4.0. Both behaved the same.
My Surface Pro 3 Win 10 is running a preview red stone fast ring version of the OS so I also tested on the latest non-preview version of Win10 in VMWare and get the same results. 
Again in all tests, the border problem is in Win 8 theme only.

The other problem mentioned (application menu opening outside application – third screenshot) occurs everywhere on any theme regardless of machine and OS if “use application menu” option is selected.

Also got a crash yesterday when I clicked on a down arrow from an icon in the title bar in your demo.

Perry

**Comment by batzen** [comment] 2016-02-20 10:23
Could you run my tool in your VM and send me the json file?
Did you make any special modifications regarding your theme on windows 10? Some of the values my tool wrote out to the json file look really weird to me.
Which DPI settings are you using?

I am also unable to reproduce your issue regarding the application menu. The only way i get it to show outside the window is by moving the window close enough to the screen-edge and then open the menu. But that's just standard popup behavior...

Any details you can provide about the crash? A Stackstrace would help a lot.

**Comment by Bortxx** [comment] 2016-02-20 11:12
Could you run my tool in your VM and send me the json file?

I will run it as soon as I find that tool again.

Did you make any special modifications regarding your theme on windows 10? Some of the values my tool wrote out to the json file look really weird to me.

No theme changes. Only changed the desktop background image and in Display settings I set “Change the size of text, apps, and other items” to 200%. But I was aware of this change and I also tested with this setting placed back to default 150% and got the same results. When I ran the tool however it was set to 200%.

Which DPI settings are you using?

Didn’t chage DPI so it must be the default. Unless this is the same setting as the one mentioned above.

I am also unable to reproduce your issue regarding the application menu. The only way i get it to show outside the window is by moving the window close enough to the screen-edge and then open the menu. But that's just standard popup behavior...

No, on mine it happens all the time except when maximized for obvious reasons. 

Any details you can provide about the crash? A Stackstrace would help a lot.

I haven’t been able to reproduce it again.

**Comment by batzen** [comment] 2016-02-21 12:21
What i can tell so far:
- Pure black border is because the GlassColor is set to #FF000000 on your machine. Which means it's pure black. On my machine, for example, it's set to #FF444D52. There is nothing i can do in this case. I don't even know how you managed to get a pure black as GlassColor. So to be honest i don't consider this a Fluent.Ribbon issue because it's just the color windows draws for the glass frame...
- I don't know why the application menu is placed totally wrong on your machine. There is nothing special we do about it's placement. It's just a popup with Placement set to PlacementMode.Relative. Do you have any placement issues with other popups in the showcase application?
- DPI settings: I can't even set it to 200%, 175% seems to be the maximum on my machine.

I don't know what i can do to reproduce all the issues. 
Things i tried so far without success:
- Changing DPI settings
- Running the showcase application in Windows Simulator

Could you try to set "Show color on Start, taskbar, action center and title bar" to on and check if the black glass frame is gone?

**Comment by Bortxx** [comment] 2016-02-21 17:42
I don’t know what glass color is since Win 10 has no aero glass anymore and doesn’t even have a way to change colors. The only color that can be set is the accent color. You can set the taskbar, start menu, and notification bar slightly transparent and you can have that transparency match your accent color but that’s it. The default IS black, for the taskbar, start menu, and notification bar. I did not change it. Here are my settings in Personalization/Colors:

Automatically pick an accent color from my background – Off
Chose your accent color:  second row, forth from the right
Show color on Start, taskbar, action center, and title bar – Off
Make Start, taskbar, and action center transparent – On

I am noticing different behavior on my preview machine "Red Stone" than on the official final "Threshold" release. Looks like Red Stone changed a little in yesterdays release. Rather than dealing with the preview builds which seems fluid, let's deal with the Threshold release which is stable and everyone is using right now. Here are more screen shots with the official Threshold release (windows 8 theme only):

Active window:
![threshhold active](https://cloud.githubusercontent.com/assets/3203210/13204152/62936d14-d87d-11e5-8617-0db87a32dab8.png)
Notice overly large borders on left, bottom, right in the active window. Color is correct.

Not-active window:
![threshhold not-active](https://cloud.githubusercontent.com/assets/3203210/13204156/6b5b7518-d87d-11e5-8f60-aa1481e7aba0.png)
Notice gray border is only on left and right. It should be all around and again wrong thickness.

Maximized window is correct in Threshold. Only Red Stone has a problem with that which will probably be fixed in final release.

As far as DPI, I did not change it. On the Redstone machine I changed the size slider in Settings/System/Display to 200%. On the Threshold machine I left the default 100%.

**Comment by Bortxx** [comment] 2016-02-21 18:01
Regarding application menu wrong placement. Yes all other apps open the menu properly. Word pad and others. Did you test with Win8 theme and also did you select "Use application menu"? It only happens if you select that setting. Also sometimes the menu doesn't stick. Press File button and menu appears. Release File button and menu goes away. It behaves like this less often. sometimes though.

**Comment by batzen** [comment] 2016-02-21 18:20
Ok, now i get the problem on windows 10 regarding borders. I was just confused because they were purely black. I will try to adjust the glass frame thickness and remove those borders.

You opened the issue with problems on maximized windows, i guess that's not the case on threshold?

So the only remaining problem seems to be the application menu appearing at the wrong position.
I did not talk about other apps, but other popups in the showcase application. One of those is location in the "Galleries" tab.

**Comment by Bortxx** [comment] 2016-02-21 21:54
But why do you have to adjust the borders yourself? Aren't you relying on an OS theme/service for that? I have an old ribbon control that was created before Windows 8 was even announced and it works perfectly in Win 8 and 10. See:
![untitled2](https://cloud.githubusercontent.com/assets/3203210/13205694/9d9c860a-d8a2-11e5-90b7-f61373cb43ba.png)
The reason I want to switch to yours is because it has the newer themes and further development on mine ended many years ago.

Did test in Galleries tab. Clicked button shown by the arrow and got this:
![untitled](https://cloud.githubusercontent.com/assets/3203210/13205696/ad2bd9e0-d8a2-11e5-82bc-3434bd18ca99.png)
Also notice that application menu opened fine on my current ribbon on same machine.

**Comment by batzen** [comment] 2016-02-21 22:49
1. Those border are drawn by windows and that's the problem. They messed these things up, for third party apps using a custom chrome, in win 10 pretty badly.
Because everything looked fine on win 8, i have to workaround these issues for win 10. As microsoft also prevents me from getting the current version of the OS reliably, i have to remove those borders completely.
You don't wanna know how messed up the win32 api regarding window management/positioning/chromes etc. is. Just try to use the WindowChrome class or the microsoft provided ribbon, which are both part of .NET, yourself.

2. I never experienced the menu issue you have and i am still unable to reproduce it. Do you have any further ideas on how to reproduce? I got no surface pro 3 to test it.
I will try to create a mini application to gather some information regarding your issue. Just give me a few days.

3. Telling me what your "old" library was doing right, does not help solving these issues.

4. Maybe you should just use the office 2013 theme which does exactly what your "old" library did (in terms of the window chrome): Draw everything itself (including window command buttons).

**Comment by Bortxx** [comment] 2016-02-22 00:53
1. I don't doubt that things are really messed up win the Win32 API and I don't envy your great work. That's way I am not doing it. Proof of this is how disjointed and bipolar if not muti-polar the UI in Windows 10 has become. There is absolutely no consistency and just looking at context menus in the OS alone, I counted over 5 different ones. 

2. The tests where done on a VM machine in VMWare on the last official version of Windows 10 Threshold. I no longer test on my Surface Pro since that is a pre-release Red Stone machine and it is not fair to expect that to work properly. We'll deal with that when Red Stone is released.

3. I know it doesn't help directly. I was just hoping that would instigate some thought about your implementation and maybe give you some clue about maybe rethinking the approach if that's even possible.

4. I really don't like the way Office 2013 looks especially the button hover overs. And that theme has the same problem with the application menu. In fact all the themes have that problem. So I'll just wait until you fix the borders and hopefully figure out the app menu issue.

I figured out how to reproduce the problem where the application menu will not stick. This is the other problem I was talking about there when you release the click on the File tab that the application menu disappears. So it is only showing if you hold down the mouse button. To reproduce, move the window outside the right side of the monitor any amount. It could even be very little. As soon as you do that, even if you put the window back so it is fully visible, from that point on the app menu will not stick.

**Comment by batzen** [comment] 2016-02-22 18:46
1. That's exactly what i am talking about. In addition to that microsoft just stopped fixing bugs in WPF.
2. That's fair. I will, as soon as i got the time, test it on red stone myself.
3. The office 2013 theme is done using that approach regarding window drawing.
4. That's something i considered to change. Thus providing more color schemes based on the office 2013 theme. But i got no time get it done... The office 2010 and windows 8 themes just require too much maintenance. Maybe i will just drop those two in favor of different color schemes for the office 2013 theme. As soon as version 4.0 of this library is released i will ask the community and act based on their response.

Regarding your application menu issue:
I wrote a small sample application.
Clicking on the first button should show a popup placed exactly as in this screenshot:
![popup-relative](https://cloud.githubusercontent.com/assets/1971030/13228247/33da6486-d99b-11e5-87cd-d7295116dbb0.png)

Please execute the attached application and tell me what it looks like, screenshot preferred, on your machine.
[PopupTests.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/141166/PopupTests.zip)

**Comment by Bortxx** [comment] 2016-02-23 00:12
These don't look right:
![untitled](https://cloud.githubusercontent.com/assets/3203210/13237192/082b5b68-d97f-11e5-9d35-9fe7fcf81a18.png)
![untitled4](https://cloud.githubusercontent.com/assets/3203210/13237194/0bc559c2-d97f-11e5-8de9-93611fc010de.png)
![untitled2](https://cloud.githubusercontent.com/assets/3203210/13237195/0d7eb09c-d97f-11e5-9e6d-3dff1abed3bb.png)
![untitled3](https://cloud.githubusercontent.com/assets/3203210/13237196/0efb057e-d97f-11e5-94de-d27592413e88.png)
![untitled5](https://cloud.githubusercontent.com/assets/3203210/13237198/106a3a10-d97f-11e5-8f00-43b8e087c81e.png)

**Comment by batzen** [comment] 2016-02-23 07:29
That's exactly what i expected...
It's no ribbon bug but i will try to create a workaround. Will send you a new version of my test tool in the next few days.

**Comment by punker76** [comment] 2016-02-23 09:28
@Bortxx I have no issues on my™ Win 7 machine, all works fine. So a short question, is your system a Tablet or Touch PC? So you should check, if your Popup/Menu settings are left or right handed.

Some informations that I found, maybe it helps you....

https://social.msdn.microsoft.com/Forums/vstudio/en-US/19ef3d33-01e5-45c5-a845-d64f9231001c/popup-positioningalignments?forum=wpf
https://msdn.microsoft.com/en-us/library/system.windows.systemparameters.menudropalignment.aspx
http://www.askvg.com/how-to-change-menu-position-from-left-to-right-in-windows-vista/
http://answers.microsoft.com/en-us/windows/forum/windows8_1-desktop/default-handedness-setting-is-right-handedness-for/cb3a9ead-7455-4255-bb7c-78ec3796faed?auth=1

/cc @batzen

**Comment by Bortxx** [comment] 2016-02-23 11:53
My Win 7 machine which made the screenshots above is a desktop computer without touch. I also tested on Win 10 in a VM also on my desktop PC and on my Win 10 Surface Pro Tablet. They all exhibit the same problem (menu sticking out the left).

Also went into my Tablet PC settings and it was already set for Right-handed. Besides all other ribbon controls don't behave like this. If it was a left-handed problem should all other ribbons open to the left too?

**Comment by batzen** [comment] 2016-02-23 18:02
The problem boils down to your machine having set SystemParameters.MenuDropAlignment to true.
As I said, I will fix this issue by using a custom popup placement which ignores this setting.

**Comment by Bortxx** [comment] 2016-02-23 21:17
The fix is good news but my curiosity is asking, who set this setting, and why has it been set on all my machines (the six I have at home and the two at work including all the VMs with mixed operating systems)? What special voodoo do I posses that puts a spell on all my machines?

**Comment by batzen** [comment] 2016-02-25 15:37
@Bortxx Maybe this is interesting for you regarding the latest insider build for windows 10.

From their changelog:
> Fixed an issue where the window borders on apps would change from accent color to black after every upgrade to a new build.

**Comment by Bortxx** [comment] 2016-02-25 17:53
Yes, I read that yesterday and thought about our problem. This reinforces why we should not test on Red Stone. So it looks like they fixed the color problem but the border thickness issue is still there, even in Threshold so that should be fixed.

**Comment by batzen** [comment] 2016-02-25 18:42
I am still working on the border problem. Removing those causes re-sizing of the window very difficult.

**Comment by batzen** [comment] 2016-02-29 17:23
@Bortxx could you test the changes i just made?

**Comment by Bortxx** [comment] 2016-02-29 18:27
Border is good. App menu opens correctly. One problem mentioned above is still there though. The app menu sometimes closes on the mouse up event immediately after mouse goes down on the File tab, causing the app menu to disappear as fast as it appeared.

Did more tests on this to find out when this happens and now I can reproduce it 100%. It always occurs when the app menu opens is such a position making the mouse up event occur on a menu item within the app menu. For example, put the window in the bottom right corner. 
![untitled](https://cloud.githubusercontent.com/assets/3203210/13404137/29a54224-decd-11e5-8ac6-e97d00e11b1c.png)
Then left click on the menu and don't release the click. Notice now the mouse is over the 6 menu item.
![untitled](https://cloud.githubusercontent.com/assets/3203210/13404427/6420d750-dece-11e5-8b4d-0522ffe42611.png)
When the mouse is released the app menu goes away. If you do it quick as most users would do, the app menu shows for only a split second then disappears.

Now notice how other ribboned Windows apps do this and probably why this problem does not exist for them.
![untitled](https://cloud.githubusercontent.com/assets/3203210/13404534/e90a6d3c-dece-11e5-8dc9-b1ec2f038042.png)
The mouse remains on the menu tab thus no problems.

**Comment by Bortxx** [comment] 2016-02-29 18:34
Also noticed this build 357 broke the top border on the Office 2013 theme.
![untitled](https://cloud.githubusercontent.com/assets/3203210/13404730/f24b3916-decf-11e5-9658-da80362eb950.png)

**Comment by batzen** [comment] 2016-02-29 22:32
Will have a look at the remaining menu issue.

The top border isn't broken. All other borders are broken. The border of the window are supposed to have the theme color in the office 2013 theme.

**Comment by batzen** [comment] 2016-02-29 23:28
As there is no way to remove the border drawn by windows itself, without introducing a myriad of new issues, i will remove the theme color border...

**Comment by Bortxx** [comment] 2016-03-01 02:27
Broken might have been the wrong word. How about "missing". You can't deny the top border is missing in Win 7. It was there in the last version. Now its completely gone in the Office 2013 theme. Also missing in Win 10 but it is easier to miss there because it is only 1px thick. That's why I magnified the screenshot so you can clearly see it gone.

**Comment by batzen** [comment] 2016-03-01 16:46
Broken is the only correct word here ;-)
It just that windows is getting in my way again...

**Comment by batzen** [comment] 2016-03-01 18:30
@Bortxx Could you have a look?
Borders and application menu should be fixed now.

**Comment by Bortxx** [comment] 2016-03-01 19:28
Looks good. If I were to be picky, the conversion throughout Windows is horizontal shift takes priority over vertical flip. In this screenshot a horizontal shift to the left would have solved the problem but instead a vertical shift occurred. 
![untitled_cr](https://cloud.githubusercontent.com/assets/3203210/13439023/7d1c471c-dfa0-11e5-86fe-98a48cc189c1.png)

**Comment by batzen** [comment] 2016-03-04 19:26
Should work correctly now.

**Comment by Bortxx** [comment] 2016-03-05 04:18
Yes that's good now. Thank you.
Found another problem. 
1. Open File menu.
2. Scroll down the list
3. Click on the right arrow of the New button
The positioning of the list very high because it seems based on the top origin of the scrolled list.
![untitled](https://cloud.githubusercontent.com/assets/3203210/13545582/c413c918-e245-11e5-8ee3-e47154c1411a.png)

**Comment by batzen** [comment] 2016-03-06 17:22
Fixed

**Comment by Bortxx** [comment] 2016-03-06 17:38
Tested and looks good.

**Comment by batzen** [comment] 2016-03-07 21:17
So this issue can, finally, be closed? ;-)

**Comment by Bortxx** [comment] 2016-03-07 21:21
This was actually several issues. All issues I have brought up here can be closed. Thanks for being patient.

**Comment by batzen** [comment] 2016-03-07 22:24
You're welcome. ;-)

**Closed by batzen** 2016-03-07 22:24 UTC
Labels: bug
