### ISSUE TITLE
GalleryItem missing hover

### ISSUE THREAD

**Issue by kkbp58** [fluentribbon/Fluent.Ribbon#1154] opened 2023-07-28 13:45 UTC
Bug is reproducible with your last showcase app.
Steps to reproduce:
1. go to galleries tab
2. open the last gallery dropdown
3. hover over gallery items - ok
4. hover over menu items - ok
5. hover over gallery items again - NOT ok, no hover state is visible, but tooltip is shown, as you can see on the attached screenshot

![galleryItemMissingHover](https://github.com/fluentribbon/Fluent.Ribbon/assets/70317536/29d5718b-4b51-45be-a4ea-ce4e6bca85ad)

---
### Environment

- Fluent.Ribbon  v10.0
- Microsoft Windows 10 Pro  Version 10.0.19045 Build 19045

**Comment by batzen** [comment] 2023-07-28 20:25
That's because the menu items are contained in a menu.
The base class (`MenuBase`) forces the mouse to be captured and only be release if clicked outside of it.
There is not much I can do on the Ribbon side to prevent this.

The custom `RibbonMenu` and `MenuItem` classes contained in this lib already contain a lot of workarounds for all sorts of issues caused by this inheritance, but the possibilities are limit.

The root cause for all those workarounds are the base classes itself, which I need to inherit from to conform with everything else those classes do and people expect from those classes.

If you just need a list of buttons (no nesting etc.) below the gallery, just use an itemscontrol/panel instead of RibbonMenu.

I hope this helps as there is nothing I can do to prevent this exact issue (aside from writing everything contained in MenuBase and MenuItem, which is way out of scope for me).

**Closed** 2023-10-27 16:27 UTC
