### ISSUE TITLE
Fluent ribbon not shown in design view

### ISSUE THREAD

**Issue by tonywei92** [fluentribbon/Fluent.Ribbon#427] opened 2017-04-21 18:35 UTC
**Place your issue description here.**

**Please do not include large amounts of code in your issue.**

---
### Environment

- Fluent.Ribbon __Latest
- Theme __Built in
- Windows __10 64bit
- .NET Framework __4.6.0

hello,please look at this video https://www.youtube.com/watch?v=qVv5B7nTnX8
at the end the design view showing FluentRibbon.
but not in mine, tested on vs2015 and vs2017, problem still persist, please help and thank you.

**Comment by batzen** [comment] 2017-04-22 08:57
Hi,

the version of Fluent.Ribbon used in the video is very old and grabbed from codeplex.
Some things done in the video are awfully wrong.
Implementing InitializeComponent by hand and just throwing an exception causes many issues later. The compiler issue should have been fixed by fixing the class name used in the xaml part of the window (`x:Class`).
Could you try to follow the instructions from http://fluentribbon.github.io/documentation/basic-setup after you added a reference to the current version (5.0.1.10) using nuget?

If that still does not help please post the error message shown by the designer or create a zip of your project and post it here.

**Comment by batzen** [comment] 2017-05-06 12:07
@tonywei92 ping

**Comment by AlexeiScherbakov** [comment] 2017-05-07 13:23
We also has this issue. I even wrote about it in (https://github.com/fluentribbon/Fluent.Ribbon/issues/389), but I cannot provide normall sample for this issue. It is very strange and I can't reproduce it - new created project with same XAML and same references working normal! But I think that is NuGet related issue (For me it happened sometimes after installing-reinstalling packages Fluent+wpflocalizeextension).
**Workaround**
After weeks of solving this issue we convert our projects to VS 2017 new format (15 version of msbuild tools) with NuGet package references. And all is working. You can try this method - it helped me

**Comment by batzen** [comment] 2017-06-05 20:42
@tonywei92 ping

**Comment by dsmprojects** [comment] 2017-06-07 03:14
I have this issue too.  If I open with VS2015 the ribbon shows in designer.  When I open the project in VS2017 it does not.  Compiles and works fine, just does not show in designer.  Starting a new project in VS2017 seemed to work fine and I'm pretty sure it worked when I stared the project.  Only after working with it for a while the designer stopped showing the ribbon.  For now I guess, I'll use VS2015 while working on the ribbon.

**Comment by CADbloke** [comment] 2017-06-09 02:48
I had the same issue in VS2015 designer with the Showcase project. I unloaded the .net 4.0 projects, deleted all the bin and obj folders in my suburb and ... you know the usual WPF routine. It eventually came good but I could only see the first tab

I also found [this SO answer](https://stackoverflow.com/a/4371164/492) to change which `Fluent:RibbonTabItem` you are viewing in the designer, namely this code...

````
<Fluent:Ribbon x:Name="ribbon"  SelectedTabIndex="1">
````
or whatever `SelectedTabIndex` you want to see. Don't forget to comment it out when you're releasing. 

Another designer workaround - I opened it in VS Blend - loaded fine.

I'm sure the "W" in WPF stands for "Weird".

**Closed** 2017-07-14 10:57 UTC
Labels: question, waiting for response

**Comment by tonywei92** [comment] 2017-07-14 11:55
hello, sorry for late reply, im busy lately. @batzen thanks for the reply, so the now FluentRibbon not work like in the video anymore, now its clear, thank you.

sincerely.

Tony

**Comment by tonywei92** [comment] 2017-07-14 11:59
@AlexeiScherbakov what is "15 version of msbuild tools"?

**Comment by AlexeiScherbakov** [comment] 2017-07-14 13:34
Project file which starts with:
<Project ToolsVersion="15.0" xmlns="
http://schemas.microsoft.com/developer/msbuild/2003">

And have NuGet project references like:

   <PackageReference Include="Extended.Wpf.Toolkit">
      <Version>3.1.0</Version>
    </PackageReference>

**Comment by batzen** [comment] 2017-07-14 13:52
Msbuild version 15 is shipped with visual studio 2017.
